safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
#url:         http://localhost:4000
githubusername: gwzz
feedburnerusername: gwzzwei
#port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

future:      true
lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   pretty
paginate:    10

#use through site.
name:        "GWZZ"
description: "This is GWZZ's Blog "
blogName:    "GWZZ"
blogDesc:    W.Z.
author:
    name:         GWZZ
    email:        zhucyw@gmail.com
description:      "This is GWZZ's Blog "

about: 			  "I am GWZZ, a Ph.D student in computer science at CASE."
follow:
    github:       https://github.com/gwzz
    feed:         http://feeds.feedburner.com/gwzzwei
description:      "This is GWZZ's Blog "

style: 			  /css/style.css

disqus:           gwzzblog

rdiscount:
  extensions: []

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']